name: Kicad

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.net'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '**.net'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs